# Generated by Django 3.2.11 on 2022-01-31 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('tripCharges', models.IntegerField(null=True)),
                ('Vat', models.IntegerField(null=True)),
                ('noOfTrips', models.IntegerField(default=0, null=True)),
                ('vatAmount', models.IntegerField(default=0, null=True)),
                ('ReceivableAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffExpenses', models.IntegerField(default=0, null=True)),
                ('officeExpenses', models.IntegerField(default=0, null=True)),
                ('truckExpenses', models.IntegerField(default=0, null=True)),
                ('otherExpenses', models.IntegerField(default=0, null=True)),
                ('totalExpenses', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='officeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('officeRent', models.IntegerField(default=0, null=True)),
                ('utilityBills', models.IntegerField(default=0, null=True)),
                ('stationary', models.IntegerField(default=0, null=True)),
                ('kitchen', models.IntegerField(default=0, null=True)),
                ('others', models.IntegerField(default=0, null=True)),
                ('totalAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='otherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('expenseName', models.CharField(max_length=200, null=True)),
                ('expenseAmount', models.IntegerField(default=0, null=True)),
                ('totalAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointName', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='staffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningDate', models.DateField(null=True)),
                ('visaExpiry', models.DateField(null=True)),
                ('passportExpiry', models.DateField(null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeid1', to='truckService.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forignUser1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('truckNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MulikaExpDate', models.DateField()),
                ('LastMaintenanceKM', models.IntegerField()),
                ('NextMaintenanceKM', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='truckFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('FuelLitres', models.IntegerField()),
                ('KMs', models.IntegerField()),
                ('fuelCost', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('truckNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truckService.trucks')),
            ],
        ),
        migrations.CreateModel(
            name='truckExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('renewalFee', models.IntegerField(default=0, null=True)),
                ('fuel', models.IntegerField(default=0, null=True)),
                ('maintenance', models.IntegerField(default=0, null=True)),
                ('repair_replace', models.IntegerField(default=0, null=True)),
                ('parking', models.IntegerField(default=0, null=True)),
                ('others', models.IntegerField(default=0, null=True)),
                ('totalAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truckex', to='truckService.trucks')),
            ],
        ),
        migrations.CreateModel(
            name='tripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('pickupPoint', models.CharField(default='', max_length=100)),
                ('nft', models.IntegerField(null=True)),
                ('Vat', models.IntegerField(default=0, null=True)),
                ('vatAmount', models.IntegerField(default=0, null=True)),
                ('ReceivableAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('DriverName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='truckService.staffprofile')),
                ('TruckNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='truckService.trucks')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='truckService.customerprofile')),
            ],
            options={
                'verbose_name': 'TripData',
                'verbose_name_plural': 'TripData',
            },
        ),
        migrations.CreateModel(
            name='staffExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('salary', models.IntegerField(default=0, null=True)),
                ('visaFee', models.IntegerField(default=0, null=True)),
                ('eidFee', models.IntegerField(default=0, null=True)),
                ('medicalIns', models.IntegerField(default=0, null=True)),
                ('overTime', models.IntegerField(default=0, null=True)),
                ('others', models.IntegerField(default=0, null=True)),
                ('totalAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='truckService.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DischargePiont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=200)),
                ('Cost', models.IntegerField(null=True)),
                ('Vat', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dischargelocation', to='truckService.location')),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeid', to='truckService.role'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forignUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
