# Generated by Django 3.2.11 on 2022-02-12 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truckService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_no', models.IntegerField()),
                ('payment_type', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('card', 'Card')], max_length=255, null=True)),
                ('payment_status', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
