# Generated by Django 3.2.11 on 2022-02-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0002_allpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdata',
            name='Discharge_Point',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dischargepoint', to='truckService.dischargepiont'),
        ),
        migrations.AlterField(
            model_name='dischargepiont',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
