# Generated by Django 3.2.11 on 2022-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0003_auto_20220213_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffexpense',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
