# Generated by Django 3.2.11 on 2022-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0005_auto_20220214_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='officeExpenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='otherExpenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='staffExpenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='totalExpenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='truckExpenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='kitchen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='officeRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='stationary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='totalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='utilityBills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='expenseAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='totalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='fuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='maintenance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='renewalFee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='repair_replace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='totalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
