# Generated by Django 3.2.11 on 2022-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0008_alter_allpayments_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeexpense',
            name='vendor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='vendor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
