# Generated by Django 3.2.11 on 2022-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0009_auto_20220222_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpayments',
            name='vendor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
