# Generated by Django 3.2.11 on 2022-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0010_allpayments_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpayments',
            name='expense_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
