# Generated by Django 3.2.11 on 2022-02-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0011_allpayments_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningDate', models.DateField(null=True)),
                ('lastLeaveDate', models.DateField(null=True)),
                ('lastReturnDate', models.DateField(null=True)),
                ('leaveRemaining', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truckService.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('jan', 'Jan'), ('feb', 'Feb'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('jun', 'Jun'), ('july', 'July'), ('august', 'August'), ('sep', 'Sep'), ('oct', 'Oct'), ('nov', 'Nov'), ('dec', 'Dec')], max_length=100)),
                ('presentDays', models.IntegerField(default=0, null=True)),
                ('absentDays', models.IntegerField(default=0, null=True)),
                ('deduction', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truckService.staffprofile')),
            ],
        ),
    ]
