# Generated by Django 3.2.11 on 2022-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0013_auto_20220311_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpayments',
            name='tripsAmount',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
