# Generated by Django 3.2.11 on 2022-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0015_auto_20220314_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpayments',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allpayments',
            name='tripsAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
