# Generated by Django 3.2.11 on 2022-03-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0016_auto_20220314_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpayments',
            name='payment_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
