# Generated by Django 3.2.11 on 2022-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0018_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='visaExpiry',
            field=models.DateField(null=True, verbose_name='Geeksforgeeks'),
        ),
    ]
