# Generated by Django 3.2.11 on 2022-04-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0019_alter_staffprofile_visaexpiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='visaExpiry',
            field=models.DateField(null=True, verbose_name='Visa/EID Expiry'),
        ),
    ]
