# Generated by Django 3.2.11 on 2022-04-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0020_alter_staffprofile_visaexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='record_Number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
