# Generated by Django 3.2.11 on 2022-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0021_customerprofile_record_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='record_Number',
            new_name='building_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='record_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
