# Generated by Django 3.2.11 on 2022-04-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0022_auto_20220412_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='managing_by',
            field=models.CharField(choices=[('owner', 'Owner'), ('realestate', 'Real Estate'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
