# Generated by Django 3.2.11 on 2022-04-12 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0023_customerprofile_managing_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='managing_by',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Real Estate', 'Real Estate'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='nft',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
