# Generated by Django 3.2.11 on 2022-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0024_auto_20220412_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deduction_reason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
