# Generated by Django 3.2.11 on 2022-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0025_attendance_deduction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffexpense',
            name='salay_paid_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
