# Generated by Django 3.2.11 on 2022-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0026_staffexpense_salay_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT%'),
        ),
        migrations.AlterField(
            model_name='staffexpense',
            name='salay_paid_by',
            field=models.CharField(choices=[('Al Ansari', 'Al Ansari'), ('By Hand', 'By Hand')], max_length=100, null=True),
        ),
    ]
