# Generated by Django 3.2.11 on 2022-04-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0028_auto_20220412_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffexpense',
            old_name='salay_paid_by',
            new_name='salary_paid_by',
        ),
    ]
