# Generated by Django 3.2.13 on 2022-04-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0029_rename_salay_paid_by_staffexpense_salary_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dataentry', 'Data Entry Operator'), ('accounts', 'Accounts')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='nft_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100, null=True)),
                ('discharge_point', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_data', to='truckService.tripdata')),
            ],
        ),
    ]
