# Generated by Django 3.2.13 on 2022-04-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0030_auto_20220422_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft_detail',
            name='discharge_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_data', to='truckService.dischargepiont'),
            preserve_default=False,
        ),
    ]
