# Generated by Django 3.2.13 on 2022-04-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0031_alter_nft_detail_discharge_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft_detail',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_data', to='truckService.tripdata'),
        ),
    ]
