# Generated by Django 3.2.13 on 2022-04-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0032_alter_nft_detail_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdata',
            name='Discharge_Point',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dischargepoint', to='truckService.dischargepiont'),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='DriverName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='truckService.staffprofile'),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='TruckNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='truckService.trucks'),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='truckService.customerprofile'),
        ),
    ]
