# Generated by Django 3.2.13 on 2022-04-23 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0033_auto_20220422_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdata',
            name='nft',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
