# Generated by Django 3.2.13 on 2022-04-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0034_alter_tripdata_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft_detail',
            name='discharge_point',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
