# Generated by Django 3.2.13 on 2022-04-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0035_alter_nft_detail_discharge_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdata',
            name='Discharge_Point',
        ),
    ]
