# Generated by Django 3.2.13 on 2022-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0036_remove_tripdata_discharge_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='billExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('vendor', models.CharField(max_length=200, null=True)),
                ('bill_no', models.IntegerField(default=0, null=True)),
                ('paid_by', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('channel', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('card', 'Card')], max_length=250, null=True)),
                ('vat', models.IntegerField(default=0, null=True, verbose_name='VAT%')),
                ('totalAmount', models.IntegerField(default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
