# Generated by Django 3.2.13 on 2022-04-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0037_billexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='staffexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT'),
        ),
    ]
