# Generated by Django 3.2.13 on 2022-04-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0039_auto_20220427_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='contact',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
