# Generated by Django 3.2.13 on 2022-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0040_auto_20220427_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='contact_person',
            field=models.CharField(default='---', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.CharField(default='---', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='estate_name',
            field=models.CharField(default='---', max_length=100, null=True),
        ),
    ]
