# Generated by Django 3.2.13 on 2022-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0041_auto_20220428_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffexpense',
            name='by_hand',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staffexpense',
            name='exchange',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
