# Generated by Django 3.2.13 on 2022-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0042_auto_20220428_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffexpense',
            name='by_hand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffexpense',
            name='exchange',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffexpense',
            name='salary_paid_by',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('By Hand', 'By Hand'), ('Both', 'Both')], max_length=100, null=True, verbose_name='Paid By'),
        ),
    ]
