# Generated by Django 3.2.13 on 2022-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0043_auto_20220428_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeexpense',
            name='paid_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='officeexpense',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='paid_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staffexpense',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='truckexpense',
            name='paid_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='truckexpense',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
