# Generated by Django 3.2.13 on 2022-04-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0044_auto_20220428_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeexpense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffa', to='truckService.staffprofile'),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffb', to='truckService.staffprofile'),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffc', to='truckService.staffprofile'),
        ),
    ]
