# Generated by Django 3.2.13 on 2022-04-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0045_auto_20220428_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffexpense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffd', to='truckService.staffprofile'),
        ),
        migrations.AlterField(
            model_name='staffexpense',
            name='salary_paid_by',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('By Hand', 'By Hand'), ('Both', 'Both')], max_length=100, null=True, verbose_name='Mode of Payment'),
        ),
    ]
