# Generated by Django 3.2.13 on 2022-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0046_auto_20220428_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckfuel',
            name='FuelLitres',
        ),
        migrations.RemoveField(
            model_name='truckfuel',
            name='KMs',
        ),
        migrations.RemoveField(
            model_name='truckfuel',
            name='fuelCost',
        ),
        migrations.AddField(
            model_name='truckfuel',
            name='fuel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckfuel',
            name='fuel_kilometers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='truckfuel',
            name='fuel_litters',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='officeexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='staffexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT Amount'),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='vat',
            field=models.IntegerField(default=0, null=True, verbose_name='VAT Amount'),
        ),
    ]
