# Generated by Django 3.2.13 on 2022-05-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0047_auto_20220501_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckfuel',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='truckfuel',
            old_name='truckNo',
            new_name='truck_no',
        ),
    ]
