# Generated by Django 3.2.13 on 2022-05-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0048_auto_20220501_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='deduction_reason',
        ),
    ]
