# Generated by Django 3.2.13 on 2022-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0049_auto_20220501_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffexpense',
            name='deduction',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
