# Generated by Django 3.2.13 on 2022-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0051_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffexpense',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
