# Generated by Django 3.2.13 on 2022-05-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0052_alter_staffexpense_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='total_fine',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='remaining_deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payable', models.IntegerField(null=True)),
                ('deduct', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sas', to='truckService.staffprofile')),
            ],
        ),
    ]
