# Generated by Django 3.2.13 on 2022-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0053_auto_20220509_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='total_fine',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remaining_deduction',
            name='deduct',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remaining_deduction',
            name='total_payable',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
