# Generated by Django 3.2.13 on 2022-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0054_auto_20220509_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffexpense',
            name='remaining_salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
