# Generated by Django 3.2.13 on 2022-05-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0055_staffexpense_remaining_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeexpense',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='truckexpense',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
