# Generated by Django 3.2.13 on 2022-05-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0056_auto_20220512_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdata',
            name='discharge_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
