# Generated by Django 3.2.13 on 2022-05-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0057_tripdata_discharge_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargepiont',
            name='location',
        ),
    ]
