# Generated by Django 3.2.13 on 2022-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0058_remove_dischargepiont_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdata',
            name='discharge_vat',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
