# Generated by Django 3.2.13 on 2022-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0059_tripdata_discharge_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdata',
            name='total_discharge_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
