# Generated by Django 3.2.11 on 2022-07-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0061_alter_tripdata_drivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdata',
            name='ReceivableAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
