# Generated by Django 3.2.11 on 2022-07-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckService', '0062_alter_tripdata_receivableamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='tripCharges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
